#
b c:\treinamento\
#
d "Schema Area":6,32;1 c:\treinamento\
#
d "Employee":7,32;1 c:\treinamento\ f 320
d "Employee":7,32;1 c:\treinamento\
#
d "Inventory":8,32;1 c:\treinamento\ f 640
d "Inventory":8,32;1 c:\treinamento\
#
d "Cust_Data":9,32;1 c:\treinamento\ f 320
d "Cust_Data":9,32;1 c:\treinamento\
#
d "Cust_Index":10,32;1 c:\treinamento\ f 320
d "Cust_Index":10,32;1 c:\treinamento\
#
d "Order":11,32;1 c:\treinamento\ f 1280
d "Order":11,32;1 c:\treinamento\
#
d "Misc":12,32;1 c:\treinamento\ f 320
d "Misc":12,32;1 c:\treinamento\
